name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      jira_ticket:
        description: 'Jira ticket'
        required: true

permissions:
  packages: write
  contents: write

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ROBOT_PAT }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: generix-beltane-robot-nonprod
          password: ${{ secrets.ROBOT_PAT }}

      -   name: Get current timestamp
          id: timestamp
          run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: |
            GITHUB_ACTOR=generix-beltane-robot-nonprod
            GITHUB_TOKEN=${{ secrets.ROBOT_PAT }}
          labels: org.opencontainers.image.source=https://github.com/beltane-generix/gnx-gcn-connector-testapp-java
          tags: ghcr.io/beltane-generix/generix-gcn-connector:${{ github.event.inputs.jira_ticket }}-${{ env.TIMESTAMP }}
          push: true